baseURL = 'https://arminsf.github.io/notes'
locale = 'en-us'
title = 'arminsf'
theme = 'hugo-theme-monochrome'

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]

[params]
navbar_title = "armin's notes"
toc_position = 'right'
math = true
enable_math = true
enable_site_search = true

[outputs]
home = ["HTML", "RSS", "JSON"]